# Netlify build
[build]
    command = "./hack/build-gitbooks.sh"
    publish = "docs/book/_book"

# Netlify redirects
[[redirects]]
    from = "https://kubernetes-sigs-cloud-provider-vsphere.netlify.com/*"
    to = "https://vsphere.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP -> HTTPS
[[redirects]]
    from = "http://vsphere.sigs.k8s.io/*"
    to = "https://vsphere.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://kubernetes-sigs-cloud-provider-vsphere.netlify.com/*"
    to = "http://vsphere.sigs.k8s.io/:splat"
    status = 301
    force = true
