apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: system:csi-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:csi-controller
  subjects:
  - kind: ServiceAccount
    name: csi-controller
    namespace: kube-system
kind: List
metadata: {}
